DROP PROCEDURE IF EXISTS updateMp;

DELIMITER //
/*VERIFICAR SI LO USAMOS, DEBIDO A QUE BUSCA POR ID DE PAGO Y ES POR ID DE PEDIDO*/
CREATE PROCEDURE updateMp ( 
  IN p_id INT,
  IN p_estado VARCHAR(50)
)
BEGIN
 UPDATE pagos SET estado = p_estado WHERE id = p_id;
END //

DELIMITER ;